# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_clusters.ipynb.

# %% auto 0
__all__ = ['data_points']

# %% ../nbs/00_clusters.ipynb 2
from nbdev.showdoc import *
import sklearn
import random 
import numpy as np
import shapely


# %% ../nbs/00_clusters.ipynb 4
class data_points:
    """Una clase que contiene a los datos"""
    def __init__(self, n, min_x = 0, min_y = 0, max_x= 1, max_y=1, seed= None):
        if seed != None:
            random.seed(seed)
        
        self.Points = np.random.uniform(low= min_x, high= max_x, size=(n, 2));
        self.Points =  [shapely.Point(x[0],x[1]) for x in self.Points]

    
    def get_points(self):
        """Una funcion que para obtener los puntos"""
        return self.Points

    def get_Multypoint(self):
        """Regresa un objeto MultiPoint con los puntos"""
        return shapely.geometry.MultiPoint(self.Points)
    
    def get_X(self):
        """Regresa las coordenadas X"""
        return [x.x for x in self.Points]

    def get_Y(self):
        """Regresa las coordenadas X"""
        return [x.x for x in self.Points]

            
    
